function signal = generateReferenceSignal()
    signal = @(t) cos(2 * pi() * t)...
            + 2 * cos(2 * pi() * 2 * t)...
            + 3 * cos(2 * pi() * 3 * t)...
            + 4 * cos(2 * pi() * 4 * t);
end